### ISSUE TITLE
Factorial method has an incorrect method signature

### ISSUE THREAD

**Issue by MasterEric** [eobermuhlner/big-math#10]
The [implementation of the factorial method](https://github.com/eobermuhlner/big-math/blob/master/ch.obermuhlner.math.big/src/main/java/ch/obermuhlner/math/big/BigDecimalMath.java#L195) provides only an integer argument, which does not match the [definition found in the README documentation](https://github.com/eobermuhlner/big-math/blob/master/README.md#bigdecimalmath).

The method should use `factorial(int, MathContext)` rather than `factorial(int)`, according to the documentation.

Additionally, for the sake of consistency, I think the factorial method should take a BigDecimal rather than an integer. [Inputting a fractional factorial should simply use the gamma function](http://mathforum.org/library/drmath/view/66119.html).

**Comment by eobermuhlner** [comment]
Thanks for the info.

I have corrected the README.

Adding the gamma function is a good idea.
I would rather make it a separate function `gamma(BigDecimal, MathContext)` and leave the `factorial(int)` function as it is.

**Comment by eobermuhlner** [comment]
Or adding an overloaded variant:
`factorial(BigDecimal, MathContext)`

**Comment by MasterEric** [comment]
The overload would definitely be a good idea. Leaving the `factorial(int)` function in place alongside an overload would prevent existing programs from breaking with the addition.

**Comment by eobermuhlner** [comment]
Implementing gamma() is definitely not trivial.

Euler's infinite product definition
https://en.wikipedia.org/wiki/Gamma_function#Euler's_definition_as_an_infinite_product
is easy to implement but after a 1000 multiplications achieves only 3 digits precision for factorial(3.0).
This will not work.

Some numerical calculation variants explained:
http://www.rskey.org/CMS/index.php/the-library/11

This one looks promising:
http://www.vttoth.com/CMS/projects/41

If nobody comes up with a working implementation in the meantime I will first finish release 2.0 (introducing BigComplex) before I attack gamma()

**Comment by eobermuhlner** [comment]
Wrote a little blog describing the development of this issue, since it is quite an interesting case.

https://github.com/eobermuhlner/big-math/blob/master/docs/markdown/gamma/gamma.md

**Comment by MasterEric** [comment]
I looked through your article, didn't realize the gamma function would be this much of a burden to implement. Thanks for your work on this issue!

**Comment by eobermuhlner** [comment]
The effort was pretty typical for a new function.

And it is fun 😄
