### ISSUE TITLE
Problem in atan2 function

### ISSUE THREAD

**Issue by sportingindividual** [eobermuhlner/big-math#17]
Hello

I think there may be a little typo in atan2() .  On line 1033 of BigDecimalMath there is

return atan(y.divide(x, 3), mathContext);

which I think should be

return atan(y.divide(x, mc), mathContext);

**Comment by eobermuhlner** [comment]
Confirmed - this is a bug.
I think your proposed fix is correct - I will test and apply it.

**Comment by eobermuhlner** [comment]
Fixed it exactly as proposed.

Thanks for finding this bug.
I will try to find some time to go through the release process soon and publish a new release.
