### ISSUE TITLE
Publish to Maven

### ISSUE THREAD

**Issue by joealbertvp** [eobermuhlner/big-math#2]
Hey, i'm working on a project and got in a situation where a i need the log function over a BigDecimal, found your project and seems great you have done a excellent work, but the limitation for me is that i can only add dependencies which are in a Maven repository, it would be great if you could publish it even if is in a beta stage, Thank you! and keep the good work!.

**Comment by eobermuhlner** [comment]
I am working on publishing it to Maven Central right now (this is more complicated than I thought).
Hope to have it ready soon.

**Comment by eobermuhlner** [comment]
The beta2 version is now available on [Maven Central](https://search.maven.org/#search%7Cga%7C1%7Cbig-math).

Please use the following dependency:
```xml
<dependency>
    <groupId>ch.obermuhlner</groupId>
    <artifactId>big-math</artifactId>
    <version>1.0-beta2</version>
</dependency>
```

**Comment by eobermuhlner** [comment]
Note: Version 1.0.0 will be released after some additional testing in the next days.

**Comment by joealbertvp** [comment]
Great! Thank you.
