### ISSUE TITLE
More efficient calculation of factorial

### ISSUE THREAD

**Issue by plokhotnyuk** [eobermuhlner/big-math#28]
Use [`split` and `recursion` routines](https://github.com/plokhotnyuk/scala-vs-java/blob/master/src/main/java/com/github/plokhotnyuk/scala_vs_java/JavaFactorial.java#L35) with cached `BigInteger` values for first 100 values.

**Comment by eobermuhlner** [comment]
Hi Andriy

Thanks for the proposed optimization.

I several times considered using parallel algorithms to optimize certain expensive calculations.
Until now I have always decided to keep the implementations single threaded in order to avoid competing with other thread pools over the CPU resources.

The current implementation of `factorial(int)` calculates on my PC the ` factorial(1000)` in 0.016831 seconds which I consider fast enough.

**Comment by eobermuhlner** [comment]
Ah - now I understand your code better.
The `ForkJoinPool` confused me, but it seems it is only used in `recursePar()`.
My fault.

I will look into it.

**Comment by eobermuhlner** [comment]
I have started with the factorial improvements.

I absolutely love your implementation in the provided link.
Especially the switching back and forth between `long` and `BigDecimal` arithmetic in `loop()` is beautyful.

I hope you agree that I base my implementation on yours.

**Comment by plokhotnyuk** [comment]
Sure, I'm agree! 

I will be happy if it helps to improve your project :)

**Comment by eobermuhlner** [comment]
I have a question about the limit in the `loop()` method.

You calculate (if I understand it correctly) the maximum value that cam
still be multiplied in `long` arithmetic without overflow:
```
final long l = Long.MAX_VALUE >> (32 - Integer.numberOfLeadingZeros(n2));
```

I believe this could also be done like this:
```
final long l = Long.MAX_VALUE / n2;
```
This solution would give a slightly larger value and therefor allow to
calculate more in `long` arithmetic before switching to `BigDecimal`.

A quick performance benchmark shows that my variant is slightly faster.
!(Comparing factorial impls)[
https://raw.githubusercontent.com/eobermuhlner/big-math/master/ch.obermuhlner.math.big.example/docu/benchmarks/images/perf_factorial_impl_loops_values_to_1000.png
]

Can you explain why you use ` Long.MAX_VALUE >> (32 -
Integer.numberOfLeadingZeros(n2)` ?
I am scared of missing a case where my solution would do arithmetic
overflow.

**Comment by eobermuhlner** [comment]
I have a question about the limit in the `loop()` method.

You calculate (if I understand it correctly) the maximum value that cam
still be multiplied in `long` arithmetic without overflow:
```java
final long l = Long.MAX_VALUE >> (32 - Integer.numberOfLeadingZeros(n2));
```

I believe this could also be done like this:
```java
final long l = Long.MAX_VALUE / n2;
```
This solution would give a slightly larger value and therefor allow to
calculate more in `long` arithmetic before switching to `BigDecimal`.

A quick performance benchmark shows that my variant is slightly faster.

![Comparing factorial impls](https://raw.githubusercontent.com/eobermuhlner/big-math/master/ch.obermuhlner.math.big.example/docu/benchmarks/images/perf_factorial_impl_loops_values_to_1000.png)


Can you explain why you use ` Long.MAX_VALUE >> (32 -
Integer.numberOfLeadingZeros(n2)` ?
I am scared of missing a case where my solution would do arithmetic
overflow.

**Comment by plokhotnyuk** [comment]
I have used that rough estimation because I payed more attention on efficiency of operations (division operation is much slower on Intel CPUs than bit counting + substraction + shift) than on general impact to performance at scale.

Also, threshold constants for switching between routines (loop/recursion/shift) were picked roughly.

**Comment by eobermuhlner** [comment]
By the way: It sounds absurd, but I often found that using `BigDecimal` was faster than `BigDecimal` even when the values where all integer values.
I assume this is due to the fact that `BigDecimal` can represent a value with exponent notation `1.23E10` more efficiently than `BigInteger` which represents it as `12300000000` and does always the full calculations on all digits.

**Comment by plokhotnyuk** [comment]
@eobermuhlner it isn't absurd, `BigDecimal` uses fast path calculations when mantissa has less than 64 bits. And only missing of some test in its API to distinguish those states (compact with `Long` and regular with `BigInteger` for the mantissa) does not allow me to use it everywhere instead of `BigInteger`.
