### ISSUE TITLE
Efficient parsing and serialization of BigInt from/to String of base 10 representation

### ISSUE THREAD

**Issue by plokhotnyuk** [eobermuhlner/big-math#30]
Current Java implementation has O(n^2) complexity.
Possible solution for big n would be using of divide and conquer approach, as described [here](https://stackoverflow.com/posts/13790024/revisions)

**Comment by plokhotnyuk** [comment]
Ups, [JDK 11 already use it for `toString`](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/999dbd4192d0f819cb5224f26e9e7fa75ca6f289/src/java.base/share/classes/java/math/BigInteger.java#L3943-L3952)... So feel free to close if it is not applicable for parsing.

**Comment by eobermuhlner** [comment]
Thanks for the hint.

My measurements show that at least the `BigDecimal(String)` constructor is O(n^2) so I will implement a split recursive version.
First experiments have been promising but I will need to get all the parsing details right.

**Comment by eobermuhlner** [comment]
I have a first version of `toBigDecimal(String)` committed.

![toBigDecimal(String) to 2000](https://raw.githubusercontent.com/eobermuhlner/big-math/master/ch.obermuhlner.math.big.example/docu/benchmarks/images/perf_bigdec_string_precisions_to_2000.png)
![toBigDecimal(String) to 10000](https://raw.githubusercontent.com/eobermuhlner/big-math/master/ch.obermuhlner.math.big.example/docu/benchmarks/images/perf_bigdec_string_precisions_to_10000.png)

**Comment by plokhotnyuk** [comment]
Eric, what a great work! 

Will you grant to adopt key part of your solution in [jsoniter-scala parser for BigDecimal](https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-core/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonReader.scala#L1388-L1466)?

**Comment by eobermuhlner** [comment]
Sure - go ahead an use the code.
The big-math library is published with MIT license and it allows this.

I am still fiddling with the code to see whether I can make it
cleaner/faster but in a few days it should be stable.

**Comment by plokhotnyuk** [comment]
Another idea for optimization of parsing of `java.math.BigDecimal` would be taking in account math context to avoid calculation of lower part which will be rounded off.

**Comment by eobermuhlner** [comment]
I agree.

**Comment by plokhotnyuk** [comment]
[Here](https://github.com/plokhotnyuk/jsoniter-scala/pull/254) is a PR with ~2x times faster parsing of BigInteger values. The algorithm still has O(n^2) complexity, just [a redundant nested loop for the addition](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/999dbd4192d0f819cb5224f26e9e7fa75ca6f289/src/java.base/share/classes/java/math/BigInteger.java#L653-L661) was removed.

**Comment by plokhotnyuk** [comment]
And finally, [a PR with using of your idea](https://github.com/plokhotnyuk/jsoniter-scala/pull/255).

Thanks you, a lot!

**Comment by plokhotnyuk** [comment]
But we still have a chance to move closer to the theoretical limit using one of proposed method for the integer multiplication in time O(n log n) [pdf] https://t.co/IltaboOoUq

**Comment by plokhotnyuk** [comment]
Also, [using of `BigDecimal.valueOf`](https://github.com/plokhotnyuk/jsoniter-scala/pull/263) gives more than 25% increase for parsing speed of small (up to 128 bits) `BigInteger` values
