### ISSUE TITLE
sqrt hangs

### ISSUE THREAD

**Issue by MikeMcl** [eobermuhlner/big-math#50]
Thanks for a great library.

Testing with OpenJDK 11 and 15, `BigDecimalMath.sqrt` seems to go into an infinite loop when passed any of these values when the precision and rounding mode are as follows:

 ```java
MathContext mc = new MathContext(10, RoundingMode.HALF_UP);
System.out.println("Testing...");
System.out.println( BigDecimalMath.sqrt( new BigDecimal("10000000000000005"), mc ) );
System.out.println( BigDecimalMath.sqrt( new BigDecimal("10000000000000006"), mc ) );
System.out.println( BigDecimalMath.sqrt( new BigDecimal("10000000000000007"), mc ) );
System.out.println( BigDecimalMath.sqrt( new BigDecimal("10000000000000008"), mc ) );
System.out.println( BigDecimalMath.sqrt( new BigDecimal("10000000000000009"), mc ) );
```

**Comment by eobermuhlner** [comment]
Thanks for the bug report.

Confirmed.
The calculated result oscillates between 100000000.0000000 and 100000000.0000001 and never reaches the calculated acceptableError of 1E-11.

As a workaround I recommend using `pow(x, 1/y)`.
