### ISSUE TITLE
sqrt rounding

### ISSUE THREAD

**Issue by MikeMcl** [eobermuhlner/big-math#51]
`BigDecimalMath.sqrt`rounding isn't always correct. Three examples:

```java
// OpenJDK 15
BigDecimal x;
MathContext mc10 = new MathContext(10, RoundingMode.HALF_UP);
MathContext mc30 = new MathContext(30, RoundingMode.DOWN);
MathContext mc40 = new MathContext(40, RoundingMode.HALF_UP);
MathContext mc60 = new MathContext(60, RoundingMode.DOWN);

System.out.println("MathContext(10, RoundingMode.HALF_UP)");
System.out.println();

x = new BigDecimal("400000005");
System.out.println("BigDecimal sqrt:      " + x.sqrt(mc10));
System.out.println("BigDecimalMath sqrt:  " + BigDecimalMath.sqrt(x, mc10));
System.out.println("Reference value:      " + BigDecimalMath.sqrt(x, mc30) + "...");
System.out.println();

x = new BigDecimal("63999999");
System.out.println("BigDecimal sqrt:      " + x.sqrt(mc10));
System.out.println("BigDecimalMath sqrt:  " + BigDecimalMath.sqrt(x, mc10));
System.out.println("Reference value:      " + BigDecimalMath.sqrt(x, mc30) + "...");
System.out.println();

System.out.println("MathContext(40, RoundingMode.HALF_UP)");
System.out.println();

x = new BigDecimal("1000000000001");
System.out.println("BigDecimal sqrt:      " + x.sqrt(mc40));
System.out.println("BigDecimalMath sqrt:  " + BigDecimalMath.sqrt(x, mc40));
System.out.println("Reference value:      " + BigDecimalMath.sqrt(x, mc60) + "...");
System.out.println();
```

```


MathContext(10, RoundingMode.HALF_UP)

BigDecimal sqrt:      20000.00012
BigDecimalMath sqrt:  20000.00013
Reference value:      20000.0001249999996093750024414...

BigDecimal sqrt:      7999.999937
BigDecimalMath sqrt:  7999.999938
Reference value:      7999.99993749999975585937309265...

MathContext(40, RoundingMode.HALF_UP)

BigDecimal sqrt:      1000000.000000499999999999875000000000062
BigDecimalMath sqrt:  1000000.000000499999999999875000000000063
Reference value:      1000000.00000049999999999987500000000006249999999996093750000...

```

**Comment by eobermuhlner** [comment]
Actually the last digit in the calculated precision is not possible to calculate absolutely correct due to rounding issues beyond the specified precision.

For this reason the documentation of the Java 9 `sqrt()` function has a caveat:
>  The value of the returned result is always within one ulp of the exact decimal value for the precision in question. If the rounding mode is HALF_UP, HALF_DOWN, or HALF_EVEN, the result is within one half an ulp of the exact decimal value.

This holds also true for the calculations in `BigDecimalMath`.
I should probably add this to the documentation of `BigDecimalMath`.

The `BigDecimalMath.sqrt()` calculates with 6 digits additional precision and then rounds the result to the specified `MathContext` - which in average is more accurate than the Java 9 implementation of `sqrt()` (at least it was last time a looked at it).

**Comment by MikeMcl** [comment]
> This holds also true for the calculations in BigDecimalMath.

Not quite. The examples show the result is off by just over half an ulp with rounding mode HALF_UP.

Anyway, I think your choice to calculate to 6 additional digits before rounding is perfectly reasonable. I just raised the issue for completeness because the behaviour isn't documented.

I think its only in Java 15 that BigDecimal sqrt gets the rounding spot on (at the cost of considerable added complexity).
