### ISSUE TITLE
BigRational toFloat() can fail in a slightly unexpected way

### ISSUE THREAD

**Issue by agdturner** [eobermuhlner/big-math#55]
Consider the following example which shows why the method fails and an alternative (Float.valueOf(x.toBigDecimal().toString())) that works more how I expected, but would fail if x could not be represented as a BigDecimal.
BigRational x = BigRational.valueOf("8.804462619980757911125181749462772084351754080848495898653087767533866267556634");
System.out.println(x.toRationalString());
System.out.println(x.toFloat());
System.out.println(Float.valueOf(x.toBigDecimal().toString()));
System.out.println(new BigDecimal("1000000000000000000000000000000000000000000000000000000000000000000000000000000").floatValue());

**Comment by agdturner** [comment]
To put this another way:
BigRational x = BigRational.valueOf("8.804462619980757911125181749462772084351");
System.out.println(x.toFloat());
System.out.println(Float.valueOf(x.toBigDecimal().toString()));

Results in the output:
NaN
8.804462

Whereas:
BigRational x = BigRational.valueOf("8.80446261998075791112518174946277208435");
System.out.println(x.toFloat());
System.out.println(Float.valueOf(x.toBigDecimal().toString()));

Results in the output:
Infinity
8.804462

Whereas:
BigRational x = BigRational.valueOf("8.8044626199807579111251817494627720843");
System.out.println(x.toFloat());
System.out.println(Float.valueOf(x.toBigDecimal().toString()));

Results in the output:
8.804462
8.804462

The behaviour of x.toFloat() created an issue for me, I would have rather the behaviour had been more like Float.valueOf(x.toBigDecimal().toString()).

**Comment by eobermuhlner** [comment]
Ah sorry. I misunderstood the failure.

You are right.
The current implementations of `toFloat()` (and actually `toDouble()` are very naive.

The new implementation will probably go in this direction (still need to test some corner cases):
```
	public float toFloat() {
		return toBigDecimal().floatValue();
	}
```
