### ISSUE TITLE
Something the matter with the 2.3.1 release?

### ISSUE THREAD

**Issue by mihxil** [eobermuhlner/big-math#61]
I noticed that using the 2.3.1 things like this happen:
```
BigDecimal pow = BigDecimalMath.pow(new BigDecimal("200"), new BigDecimal("-200"), new MathContext(6));
System.out.println("" + pow);
```
prints `0`, which would obviously be a bug. I thought I'd look into it, and it costed me some time, but the code which is on maven central as 2.3.1 for this class doesn't seem to be right.  

E.g. this`pow` function ends with 
```return roundAbsolutePrecision(result, mathContext);``` (which btw seems to cause the problem)

which I can't even find in the repository.

I don't know what happened, but something seems to be rather odd?

**Comment by eobermuhlner** [comment]
This is very strange.

`roundAbsolutePrecision()` is still under development and should not be part of release 2.3.1

I must have made a mistake during the build of 2.3.1 and accidentally created the published library from a workspace with uncommitted changes.
I will fix this as soon as possible.

I apologize for the inconvenience.
