### ISSUE TITLE
1.5^(1e10) gives incorrect result due to integer overflow in expIntegralFractional

### ISSUE THREAD

**Issue by skluyskens** [eobermuhlner/big-math#7]
integralPart.intValue() does not give correct result in that case
With integralPart.longValueExact() you can fix this specific case e.g.

**Comment by eobermuhlner** [comment]
Bug confirmed.

The result of pow(1.5, 1e10) is outside the range that BigDecimal supports for the scale (which only allows int values).
This should throw an exception.

**Comment by eobermuhlner** [comment]
Fix is pushed and will be in the next release.

**Comment by skluyskens** [comment]
Result of 1.5^(1e10) is +- 3.6e1760912590, exponent 1760912590 can be represented as integer. Wouldn't it be an option to use a long for the pow's y parameter? Just a remark, the current solution is good enough for my needs.

**Comment by eobermuhlner** [comment]
You are right, the result has the exponent still in the integer range and although the y value is outside of integer range the calculation should still work.

I have not yet decided whether I should go with your proposed solution using longValueExact() or whether I should make it work with all BigDecimal y values that have no fractional part.

**Comment by eobermuhlner** [comment]
I decided to go the full way.

`pow(BigDecimal, int)` is changed to `pow(BigDecimal, long)`
that should handle your case.

Added `BigDecimal powInteger(BigDecimal x, BigDecimal integerY, MathContext mathContext)`
that can calculate the pow() with integral values beyond `longValueExact()`.
This implementation is slower than `pow(BigDecimal, long)` so it is only used if necessary.

**Comment by eobermuhlner** [comment]
Released in 2.0.0
