### ISSUE TITLE
[question] Double.POSITIVE_INFINITE, isNAN functions available?

### ISSUE THREAD

**Issue by archenroot** [eobermuhlner/big-math#8]
This is some kind of library! good stuff.

I have a question about having representation of following Double only related JDK functions:

- POSITIVE_INFINITE,
- isNan()

I have especially problem with positive_infinite representation in BigDecimal...

What do you think to add this constant from Double into your library as method with mathcontext as additional parameter for precision config.

**Comment by eobermuhlner** [comment]
Thanks for your feedback.

Yes, it is very unfortunate that BigDecimal itself does not have a representation of infinite values and NaN.
I have planned to add this functionality to the BigFloat wrapper but it was never urgent enough...

I do not see a solution to add it to BigDecimalMath.

If you have an idea, please hack it up and send me a proposal (pull request would probably be best, but code example in this conversation would also be fine).
